### ISSUE TITLE
Now when code merged with espruino where is API/documentation?

### ISSUE THREAD

**Issue by soswow** [esp8266-espruino/esp8266-espurino#5]
I see some stuff here https://github.com/esp8266-espruino/esp8266-espurino/wiki/05-User-Guide but this repo is seems to be abandoned , where latest docs are?
Also this page http://www.espruino.com/ESP8266 confuses me. Looks like this is interface WITH esp8266, and not applicable in this case (where esp8266 hosts espruino)

**Comment by nkolban** [comment]
Howdy ... this repository is now closed awaiting its deletion ... see this page:

https://github.com/esp8266-espruino/esp8266-espurino

All the artifacts in this repository were merged into the master Espruino repository found here:

https://github.com/espruino/Espruino

At present, Espruino running on the ESP8266 is considered "beta" however it appears to be stable and very close to be functionally complete.   Firmware images can be downloaded from here:

https://github.com/espruino/EspruinoBuilds/tree/master/ESP8266

The forum for discussing Espruino can be found here:

http://forum.espruino.com/

And discussion of running Espruino natively on the ESP8266 is also desired and allowed.

There is a gitter chat stream for those who want to try live chat ... it can be found here:

https://gitter.im/espruino/Espruino

The latest docs on running Espruino on the ESP8266 can be found here ...

https://github.com/espruino/Espruino/tree/master/targets/esp8266/docs

But this is more a holding place until such time as the beta ends and ESP8266 becomes a a first class Espruino host at which time the docs will be merged into the formal Espruino docs found here:

http://www.espruino.com/Reference
